export const DEFAULT_CONTACTS=[
  {id:1,type:"LP",name:"Jeff Aeder",firm:"JDI Realty",email:"jaeder@jdirealty.com",phone:"(773) 680-8490",status:"Deck sent",priority:"Medium",likelihood:25,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark ($150k via Mah Jong LLC)",howWeKnowThem:"2616 N Clark investor",nextStep:"",notes:"Data room granted Mar 18.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:2,type:"LP",name:"Daniel Kahan",firm:"JDI Realty",email:"DKahan@jdirealty.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:25,expectedAmount:12500,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark ($150k via Mah Jong LLC)",howWeKnowThem:"2616 N Clark investor",nextStep:"",notes:"Data room granted Mar 18.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:3,type:"LP",name:"Dominic Sergi",firm:"West Shore Capital",email:"ds@westshorecg.com",phone:"(630) 688-3832",status:"Deck sent",priority:"High",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark, 1431 W Taylor, 801 W Madison",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"Data room granted Mar 18.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:4,type:"LP",name:"Anthony Casaccio",firm:"West Shore Capital",email:"ac@westshorecg.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:25000,tag:"2616 N Clark",relationship:"Co-investor with Dominic Sergi across multiple ECG deals",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:5,type:"LP",name:"Eric Augustyn",firm:"August Hill",email:"eric@augusthill.co",phone:"(203) 500-6712",status:"Data room accessed",priority:"Medium",likelihood:50,expectedAmount:25000,tag:"18 W Investor",relationship:"Prior investor in 18 W Merchant ($25k via UT-STL LLC)",howWeKnowThem:"18 W Merchant investor",nextStep:"",notes:"Data room accessed Mar 9.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:6,type:"LP",name:"Vann Avedisian",firm:"New Bond",email:"vavedisian@newbond.com",phone:"(312) 310-9580",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:7,type:"LP",name:"Thomas Bohac",firm:"SB Group LLC",email:"thomas@sbgroupllc.com",phone:"(312) 515-1708",status:"In conversation",priority:"High",likelihood:50,expectedAmount:50000,tag:"18 W Investor",relationship:"Prior investor in 18 W Merchant ($50k personally)",howWeKnowThem:"18 W Merchant investor",nextStep:"Follow up after April 9 meeting",notes:"Phone call Mar 10.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:8,type:"LP",name:"Ryan Brown",firm:"Chaifetz Group",email:"rbrown@chaifetzgroup.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:9,type:"LP",name:"Michael Carney",firm:"Starshot Ventures",email:"michael@starshot.ventures",phone:"",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:10,type:"LP",name:"Ross Chaifetz",firm:"Chaifetz Group",email:"rosschaifetz@chaifetzgroup.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:11,type:"LP",name:"John Daley",firm:"Daley Strategy",email:"John@daleystrategy.com",phone:"",status:"Data room accessed",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($25k)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"Data room accessed Mar 18.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:12,type:"LP",name:"Patrick R. Daley",firm:"",email:"patrickrdaley@gmail.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($75k via Tur Holdings)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:13,type:"LP",name:"Anthony Disano",firm:"Parkvue Realty",email:"adisano@parkvuerealty.com",phone:"(312) 296-0950",status:"Data room accessed",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"18 W Investor",relationship:"Prior investor in 18 W Merchant ($50k via AS LLC)",howWeKnowThem:"18 W Merchant investor",nextStep:"",notes:"Data room accessed Mar 10.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:14,type:"LP",name:"Connor P. Doherty",firm:"",email:"Connordoherty33@gmail.com",phone:"(802) 236-7887",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($50k personally)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:15,type:"LP",name:"Dan Drexler",firm:"Crown Chicago",email:"ddrexler@crown-chicago.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:16,type:"LP",name:"Benjamin J. Firestone",firm:"Blueprint HCRE",email:"bfirestone@blueprintHCRE.com",phone:"(312) 545-4505",status:"Deck sent",priority:"High",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 19400 Ravine ($50k), 2616 N Clark ($25k), 801 W Madison ($50k)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:17,type:"LP",name:"Harry Quaid",firm:"Realty ADS",email:"harry.quaid@realtyads.com",phone:"(847) 436-2521",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($25k via HAM Wave LLC)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:18,type:"LP",name:"Paul Gassel",firm:"WWM Investment",email:"pgassel@wwminvestment.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($75k personally)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:19,type:"LP",name:"Jimmy Georgantas",firm:"ECG / NBHD Hotels",email:"jimmy@nbhdhotels.com",phone:"(815) 302-7392",status:"Committed",priority:"High",likelihood:100,expectedAmount:13126,tag:"Co-GP",relationship:"Co-GP internal",howWeKnowThem:"Internal",nextStep:"",notes:"Committed.",bio:"",whatTheyCareAbout:"",title:"Co-GP",linkedinUrl:""},
  {id:20,type:"LP",name:"Alex Gilbert",firm:"Brightcare Direct",email:"alex.gilbert@brightcaredirect.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark ($25k)",howWeKnowThem:"2616 N Clark investor",nextStep:"",notes:"Missing phone.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:21,type:"LP",name:"Julie & Gregory Goldstein",firm:"Metis MD",email:"ggoldstein@metismd.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($50k via Goldstein Trust)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:22,type:"LP",name:"Zachary Goodman",firm:"Goodman Enterprises",email:"zach.s.goodman@gmail.com",phone:"(248) 763-6009",status:"Deck sent",priority:"High",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 19400 Ravine ($50k), 2616 N Clark ($50k)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:23,type:"LP",name:"Jonathan Gordon",firm:"ECG",email:"jonomg@yahoo.com",phone:"(773) 710-4748",status:"Committed",priority:"High",likelihood:100,expectedAmount:null,tag:"Co-GP",relationship:"Primary Owner of ECG",howWeKnowThem:"Internal",nextStep:"",notes:"Co-GP.",bio:"",whatTheyCareAbout:"",title:"Primary Owner",linkedinUrl:""},
  {id:24,type:"LP",name:"David Alan Helfand",firm:"EQC Real Estate",email:"dhelfand@eqcre.com",phone:"(312) 965-1200",status:"Deck sent",priority:"High",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 19400 Ravine ($100k), 2616 N Clark ($100k), 801 W Madison ($75k)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:25,type:"LP",name:"Michael Hobbs",firm:"",email:"mikehobbs1919@gmail.com",phone:"",status:"Committed",priority:"High",likelihood:100,expectedAmount:257260,tag:"Co-GP",relationship:"Co-GP. Prior investor in 18 W Merchant ($75k) and NB Expansion GP Fund",howWeKnowThem:"Co-GP",nextStep:"",notes:"Committed.",bio:"",whatTheyCareAbout:"",title:"Co-GP",linkedinUrl:""},
  {id:26,type:"LP",name:"Ross Holdren",firm:"LandEx LLC",email:"ross@landexllc.com",phone:"(720) 335-9996",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:27,type:"LP",name:"William Hughes",firm:"",email:"WilliamHughes400@outlook.com",phone:"(847) 867-8114",status:"Data room accessed",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark ($25k)",howWeKnowThem:"2616 N Clark investor",nextStep:"",notes:"Data room accessed Mar 19.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:28,type:"LP",name:"Jerry J. Jaeger",firm:"",email:"jjjalj425@aol.com",phone:"(847) 337-4800",status:"Deck sent",priority:"High",likelihood:25,expectedAmount:50000,tag:"18 W Investor",relationship:"$100k per deal across 5 ECG deals",howWeKnowThem:"18 W Merchant investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:29,type:"LP",name:"Greg Janes",firm:"Evelyn Alan Investments",email:"evelynalan@janesfamily.org",phone:"(319) 899-2423",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark ($100k)",howWeKnowThem:"2616 N Clark investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:30,type:"LP",name:"Michael Kaulentis",firm:"",email:"michael.kaulentis@gmail.com",phone:"(312) 330-8200",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark ($50k)",howWeKnowThem:"2616 N Clark investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:31,type:"LP",name:"Benny Kay",firm:"Gray Capital Investors",email:"benny_kay@graycapitalinvestors.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:32,type:"LP",name:"Kevin P. Kolb",firm:"Altitude Chicago",email:"kevin@altitudechicago.com",phone:"(312) 282-4375",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($25k)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:33,type:"LP",name:"Bennett Kramer",firm:"",email:"bennettmkramer@gmail.com",phone:"(914) 552-3735",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($25k)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:34,type:"LP",name:"Jack Krasaeath",firm:"Diversey Real Estate",email:"jack.krasaeath@diverseyrealestate.com",phone:"(773) 263-4979",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:25000,tag:"18 W Investor",relationship:"Prior investor in 18 W Merchant and 2616 N Clark ($25k each)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:35,type:"LP",name:"Liam Krehbiel",firm:"Topography",email:"krehbiel@topography.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"Family Office.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:36,type:"LP",name:"Keegan Kuhn",firm:"",email:"keegankuhn@gmail.com",phone:"(773) 569-5846",status:"Deck sent",priority:"High",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 2616 N Clark ($100k)",howWeKnowThem:"2616 N Clark investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:37,type:"LP",name:"Garrett Lalich",firm:"Buttons Investments",email:"garrett.lalich@gmail.com",phone:"(773) 951-9153",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark ($50k)",howWeKnowThem:"2616 N Clark investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:38,type:"LP",name:"Josh Leitner",firm:"3J Capital",email:"josh@leitnerprops.com",phone:"(917) 656-2138",status:"Deck sent",priority:"High",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Major repeat investor — 19400 Ravine ($100k), 1431 W Taylor ($182k+), 801 W Madison ($100k)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:39,type:"LP",name:"Anthony Leopardo",firm:"Alexander West Capital",email:"ajl@alexanderwestcapital.com",phone:"(847) 707-2013",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:40,type:"LP",name:"Eli Levenfeld",firm:"Levenfeld Investments",email:"elevenfeld97@gmail.com",phone:"(847) 508-7594",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($25k)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:41,type:"LP",name:"Scott Levenfeld",firm:"",email:"slevenfeld@earthlink.net",phone:"",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:42,type:"LP",name:"Sam Levinson",firm:"Lev Capital",email:"levcapital@aol.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"Family Office.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:43,type:"LP",name:"Barry Levy",firm:"",email:"bil1323@sbcglobal.net",phone:"",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($25k via Barry I. Levy Trust)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"Missing phone.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:44,type:"LP",name:"Israel Levy",firm:"Israel Levy Revocable Trust",email:"israellevy@msn.com",phone:"(847) 858-6601",status:"Deck sent",priority:"High",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark ($150k)",howWeKnowThem:"2616 N Clark investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:45,type:"LP",name:"Noah Levy",firm:"",email:"Noahnlevy@gmail.com",phone:"(847) 477-4613",status:"Deck sent",priority:"High",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark ($100k) and 801 W Madison ($100k)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:46,type:"LP",name:"Ross Levy",firm:"",email:"levy.ross@gmail.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($25k via Ross Levy Trust)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:47,type:"LP",name:"Dean Lurie",firm:"SPK Law",email:"dlurie@spklaw.com",phone:"(312) 286-5005",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:25000,tag:"18 W Investor",relationship:"Prior investor in 19400 Ravine ($25k) and 18 W Merchant ($25k)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:48,type:"LP",name:"Drew Marticke",firm:"",email:"dmarticke@gmail.com",phone:"(917) 860-2630",status:"Deck sent",priority:"High",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Major repeat investor — 19400 Ravine ($200k) and 2616 N Clark ($200k)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:49,type:"LP",name:"Ethan Meers",firm:"Kinship Capital",email:"ethan.meers@kinshipcapital.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:50,type:"LP",name:"Alan Mellovitz",firm:"",email:"amellov2@gmail.com",phone:"(847) 363-5860",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($25k)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:51,type:"LP",name:"Jordan Mellovitz",firm:"3 Edgewood",email:"jordan.mellovitz@3edgewood.com",phone:"(847) 254-5860",status:"Data room accessed",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($33k)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"Data room accessed Mar 18.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:52,type:"LP",name:"Jonathan Metzl",firm:"Cushman & Wakefield",email:"jonathan.metzl@cushwake.com",phone:"(773) 771-9680",status:"Deck sent",priority:"High",likelihood:50,expectedAmount:50000,tag:"18 W Investor",relationship:"Prior investor in 19400 Ravine ($50k), 18 W Merchant ($50k), 801 W Madison ($50k)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:53,type:"LP",name:"Max Meyers",firm:"Anagram Capital",email:"max@anagramcapital.com",phone:"(312) 933-5498",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"Private Equity.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:54,type:"LP",name:"Ian Murphy",firm:"IJM Ventures",email:"ian@ijmurphyventures.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:25000,tag:"18 W Investor",relationship:"Prior investor in 18 W Merchant ($25k)",howWeKnowThem:"18 W Merchant investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:55,type:"LP",name:"Steven B. Nasatir",firm:"JUF",email:"stevennasatir@juf.org",phone:"(312) 560-7597",status:"Deck sent",priority:"High",likelihood:50,expectedAmount:25000,tag:"18 W Investor",relationship:"Prior investor in 18 W Merchant ($25k), 2616 N Clark ($25k), 801 W Madison ($50k)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:56,type:"LP",name:"Tony Olson",firm:"Webster Capital Management",email:"tolson@webstercm.com",phone:"(847) 867-7932",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:57,type:"LP",name:"Noah O'Neill",firm:"Stone Real Estate",email:"noah@stonerealestate.com",phone:"(312) 343-2683",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($25k)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:58,type:"LP",name:"Mason Phelps",firm:"",email:"mason1741@gmail.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:59,type:"LP",name:"Josh Piuma",firm:"KF Partners",email:"josh@kf-partners.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"Family Office.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:60,type:"LP",name:"Lisa Rome",firm:"Lisa S. Rome Revocable Trust",email:"luckymia18@gmail.com",phone:"(918) 691-6446",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark ($25k)",howWeKnowThem:"2616 N Clark investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:61,type:"LP",name:"Daniel Rosen",firm:"Renovo Financial",email:"drosen@renovofinancial.com",phone:"",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:25000,tag:"18 W Investor",relationship:"Prior investor in 19400 Ravine ($25k) and 18 W Merchant ($25k)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"Missing phone.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:62,type:"LP",name:"Robert Rothschild",firm:"Rothschild Agency",email:"rob@rothschildagency.com",phone:"(219) 680-6960",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:25000,tag:"18 W Investor",relationship:"Prior investor in 18 W Merchant ($50k) and 2616 N Clark ($25k)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:63,type:"LP",name:"Allen Samuel",firm:"",email:"allenbsam@gmail.com",phone:"(312) 498-4905",status:"In conversation",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"18 W Investor",relationship:"Prior investor in 18 W Merchant ($50k via Lesley M. Samuel Revocable Trust)",howWeKnowThem:"18 W Merchant investor",nextStep:"",notes:"Data room accessed Mar 10.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:64,type:"LP",name:"Joe Sauer",firm:"Abbell",email:"joe@abbell.com",phone:"(312) 961-8748",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:25000,tag:"18 W Investor",relationship:"Prior investor in 19400 Ravine ($25k) and 18 W Merchant ($25k)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:65,type:"LP",name:"Roger Schoenfeld",firm:"CK Capital",email:"rschoenfeld@ckcap.com",phone:"(847) 732-2162",status:"In conversation",priority:"High",likelihood:50,expectedAmount:50000,tag:"18 W Investor",relationship:"Prior investor in 18 W Merchant ($50k), 2616 N Clark ($50k), 801 W Madison ($50k)",howWeKnowThem:"Multi-deal investor",nextStep:"Reach out after April 9 meeting",notes:"Phone call Mar 18 — LIKELY IN FOR $50K.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:66,type:"LP",name:"Lawrence Segal",firm:"Lawrence Segal Trust",email:"lawrence@legalsegal.com",phone:"(310) 550-4840",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 2616 N Clark ($50k)",howWeKnowThem:"2616 N Clark investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:67,type:"LP",name:"Kurt Siedensticker",firm:"Starshot Ventures",email:"kurt@starshot.ventures",phone:"",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:68,type:"LP",name:"Morris Silverman",firm:"USAN Financial",email:"ms@usanfsc.com",phone:"(847) 919-4800",status:"Deck sent",priority:"High",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Major repeat investor — 2616 N Clark ($100k), 1431 W Taylor ($273k+), 801 W Madison ($300k)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:69,type:"LP",name:"Richard Silverman",firm:"MJK Real Estate",email:"rs@mjkre.com",phone:"(847) 530-9512",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark ($50k), 1431 W Taylor ($59k+)",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:70,type:"LP",name:"Mike Simpson",firm:"Torburn",email:"msimpson@torburn.com",phone:"(847) 858-5103",status:"Deck sent",priority:"Medium",likelihood:null,expectedAmount:null,tag:"",relationship:"",howWeKnowThem:"",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:71,type:"LP",name:"Seth Singerman",firm:"Singerman Real Estate",email:"ssingerman@singermanre.com",phone:"(312) 543-8599",status:"Data room accessed",priority:"High",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark ($50k)",howWeKnowThem:"2616 N Clark investor",nextStep:"",notes:"Data room accessed Mar 19.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:72,type:"LP",name:"Shoshana Vernick",firm:"Avathon Capital",email:"svernick@avathoncapital.com",phone:"(312) 286-4527",status:"Data room accessed",priority:"High",likelihood:50,expectedAmount:100000,tag:"18 W Investor",relationship:"Major repeat investor — 5 deals, $100k+ each",howWeKnowThem:"Multi-deal investor",nextStep:"",notes:"Kevin Vernick accessed data room Mar 9.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:73,type:"LP",name:"Jay Weaver",firm:"Quartz Lake Capital",email:"weaver@quartzlakecap.com",phone:"(312) 925-0792",status:"Committed",priority:"High",likelihood:100,expectedAmount:128630,tag:"Co-GP",relationship:"Co-GP. NB Expansion GP Fund ($102.9k)",howWeKnowThem:"Co-GP",nextStep:"",notes:"Committed.",bio:"",whatTheyCareAbout:"",title:"Co-GP",linkedinUrl:""},
  {id:74,type:"LP",name:"Tyler Weinberg",firm:"2616 N Clark Investors LLC",email:"tylerweinberg@gmail.com",phone:"(410) 913-6602",status:"Deck sent",priority:"High",likelihood:50,expectedAmount:50000,tag:"2616 N Clark",relationship:"Prior investor in 2616 N Clark ($250k)",howWeKnowThem:"2616 N Clark investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:75,type:"LP",name:"Kevin Werner",firm:"Renovo Financial",email:"kevin@renovofinancial.com",phone:"(312) 543-1379",status:"Committed",priority:"High",likelihood:100,expectedAmount:257260,tag:"Co-GP",relationship:"Co-GP. Prior investor in 19400 Ravine ($75k), 18 W Merchant ($75k)",howWeKnowThem:"Co-GP",nextStep:"",notes:"Committed.",bio:"",whatTheyCareAbout:"",title:"Co-GP",linkedinUrl:""},
  {id:76,type:"LP",name:"Brad Zaransky",firm:"MZ Capital Partners",email:"brad@mzcapitalpartners.com",phone:"(847) 370-9004",status:"Deck sent",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"Grand Beach",relationship:"Prior investor in 19400 Ravine ($25k)",howWeKnowThem:"Grand Beach investor",nextStep:"",notes:"",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:77,type:"LP",name:"Lisa Zhao",firm:"",email:"lisa.q.zhao@gmail.com",phone:"(312) 307-4185",status:"Data room accessed",priority:"Medium",likelihood:50,expectedAmount:50000,tag:"18 W Investor",relationship:"Prior investor in 18 W Merchant ($50k via Qin Lisa Zhao Trust)",howWeKnowThem:"18 W Merchant investor",nextStep:"",notes:"Data room accessed Mar 16.",bio:"",whatTheyCareAbout:"",title:"",linkedinUrl:""},
  {id:2001,type:"Lender",name:"Kevin Murphy",firm:"Burling Bank",email:"kmurphy@burlingbank.com",phone:"",status:"Outreach sent",priority:"Medium",projectedLoanAmount:"",loanType:"Construction-to-perm",dealsDone:"",minLoanSize:"",maxLoanSize:"",ltcAppetite:"",geographies:"",bio:"",nextStep:"Follow-up",notes:"Owner: Jimmy.",title:"",linkedinUrl:""},
  {id:2002,type:"Lender",name:"Bruce Piekarski",firm:"Horizon Bank",email:"bpiekarski@horizonbank.com",phone:"",status:"Term sheet requested",priority:"High",projectedLoanAmount:"",loanType:"Construction-to-perm",dealsDone:"",minLoanSize:"",maxLoanSize:"",ltcAppetite:"",geographies:"",bio:"",nextStep:"Receive term sheet",notes:"Co-contact: Stacey Stephens.",title:"",linkedinUrl:""},
  {id:2003,type:"Lender",name:"Jim Lesko",firm:"Green State Credit Union",email:"",phone:"",status:"Outreach sent",priority:"Medium",projectedLoanAmount:"",loanType:"Construction-to-perm",dealsDone:"",minLoanSize:"",maxLoanSize:"",ltcAppetite:"",geographies:"",bio:"",nextStep:"Follow-up",notes:"Owner: Jimmy.",title:"",linkedinUrl:""},
  {id:2004,type:"Lender",name:"Mark Ptacek",firm:"Heartland Bank",email:"",phone:"",status:"Outreach sent",priority:"Medium",projectedLoanAmount:"",loanType:"Construction-to-perm",dealsDone:"",minLoanSize:"",maxLoanSize:"",ltcAppetite:"",geographies:"",bio:"",nextStep:"Follow-up",notes:"Co-contact: Jeff Wisenwski.",title:"",linkedinUrl:""},
  {id:2005,type:"Lender",name:"Ben Bochnowski",firm:"Centier Bank",email:"",phone:"",status:"Outreach sent",priority:"Medium",projectedLoanAmount:"",loanType:"Construction-to-perm",dealsDone:"",minLoanSize:"",maxLoanSize:"",ltcAppetite:"",geographies:"",bio:"",nextStep:"Follow-up",notes:"Owner: Jimmy.",title:"",linkedinUrl:""},
  {id:2006,type:"Lender",name:"Chris Metcalf",firm:"PanAmerican Bank",email:"",phone:"",status:"Outreach sent",priority:"High",projectedLoanAmount:"",loanType:"Construction-to-perm",dealsDone:"",minLoanSize:"",maxLoanSize:"",ltcAppetite:"",geographies:"",bio:"",nextStep:"In-person meeting",notes:"Meeting 3/26 @ 2PM.",title:"",linkedinUrl:""},
];

export const DEFAULT_MILES=[
  {id:1,label:"Vendor selection (remediation/demo)",start:"2026-07-27",end:"2026-07-31",phase:"Approvals",notes:"Selecting group; group submits remediation request to state upon selection."},
  {id:2,label:"State remediation approval",start:"2026-08-03",end:"2026-08-14",phase:"Approvals",notes:"Statutory 10 business day review period following submission."},
  {id:3,label:"Right-of-way permit",start:"2026-07-27",end:"2026-08-07",phase:"Approvals",notes:"Allows occupation of sidewalk/street. Fire hydrant contract already in place through Oslo."},
  {id:4,label:"Fencing installation",start:"2026-08-10",end:"2026-08-14",phase:"Site Prep",notes:"Chainlink, L-shape, ties into existing fencing including white fence. Mesh decision open."},
  {id:5,label:"Tree pruning / removal",start:"2026-07-27",end:"2026-08-14",phase:"Site Prep",notes:"Nate and Christian (arborist) connecting this week to set dig plans and timeline."},
  {id:6,label:"Remediation",start:"2026-08-17",end:"2026-08-21",phase:"Remediation/Demo",notes:"Budgeted 5 business days (est. 2\u20133). Demo permit already in hand."},
  {id:7,label:"Demolition",start:"2026-08-24",end:"2026-09-04",phase:"Remediation/Demo",notes:"Up to 10 business days (conservative). Same group performing remediation."},
  {id:8,label:"Excavation",start:"2026-09-07",end:"2026-09-11",phase:"Remediation/Demo",notes:"Up to 5 business days. Same demo group."},
  {id:9,label:"Structural (concrete & steel)",start:"2026-09-14",end:"2026-09-30",phase:"Structural",notes:"Target: GMP locked and ready for substantial construction in September."},
];

export const DEFAULT_TASKS=[
  {id:1,title:"Close on 109 N Barton parcel",owner:"Jonathan",due:"2026-06-01",priority:"High",status:"In progress",notes:"Under contract. Needs ZBA variance and final site plan."},
  {id:2,title:"Submit final site plan",owner:"Jimmy",due:"2026-04-15",priority:"High",status:"To do",notes:""},
  {id:3,title:"Complete LP fundraising",owner:"Matt",due:"2026-05-15",priority:"High",status:"In progress",notes:"77 prospects. Roger Schoenfeld likely in for $50k — follow up after April 9."},
  {id:4,title:"Secure construction loan",owner:"Jimmy",due:"2026-06-01",priority:"High",status:"In progress",notes:"PanAmerican meeting 3/26. Horizon term sheet pending."},
  {id:5,title:"Finalize GMP with OSLO Builders",owner:"Jonathan",due:"2026-05-01",priority:"High",status:"To do",notes:""},
  {id:6,title:"Engage interior design team",owner:"Jackson",due:"2026-07-01",priority:"Medium",status:"To do",notes:"Rebel House Interior Design on project team."},
  {id:7,title:"Long-lead procurement",owner:"Jimmy",due:"2026-07-01",priority:"Medium",status:"To do",notes:"FF&E & OS&E budget: $542,932"},
  {id:8,title:"Building permit submittal",owner:"Jonathan",due:"2026-05-01",priority:"High",status:"To do",notes:""},
];

export const VE_ITEMS=[
  {id:1,number:1,title:"Trellis",total:-49790,category:"Structural/Exterior",
    lines:[
      {desc:"Trellis Steel",qty:1,unit:"ls",price:-15000,sub:-15000},
      {desc:"Trellis Cedar",qty:1,unit:"allow",price:-8000,sub:-8000},
      {desc:"Trellis Roof & Gutter",qty:1,unit:"ls",price:-15000,sub:-15000},
      {desc:"Trellis Paint",qty:1,unit:"ls",price:-2000,sub:-2000},
      {desc:"Trellis Footings",qty:1,unit:"ls",price:-6000,sub:-6000},
      {desc:"Insurance (1.00%)",qty:null,unit:"",price:-15000,sub:-150},
      {desc:"Overhead and Fee (2.75%)",qty:null,unit:"",price:-46150,sub:-1269},
      {desc:"Contingency (5.00%)",qty:null,unit:"",price:-47419.13,sub:-2371},
    ]},
  {id:2,number:2,title:"Steel Deck Edge Detail",total:-16345,category:"Structural",
    lines:[
      {desc:"Steel Stiffeners and detailing",qty:1,unit:"allow",price:-15000,sub:-15000},
      {desc:"Insurance (1.00%)",qty:null,unit:"",price:-15000,sub:-150},
      {desc:"Overhead and Fee (2.75%)",qty:null,unit:"",price:-15150,sub:-417},
      {desc:"Contingency (5.00%)",qty:null,unit:"",price:-15566.63,sub:-778},
    ]},
  {id:3,number:3,title:"Truss Reconfiguration",total:-16345,category:"Structural",
    lines:[
      {desc:"Reconfiguration of Trusses",qty:1,unit:"allow",price:-15000,sub:-15000},
      {desc:"Insurance (1.00%)",qty:null,unit:"",price:-15000,sub:-150},
      {desc:"Overhead and Fee (2.75%)",qty:null,unit:"",price:-15150,sub:-417},
      {desc:"Contingency (5.00%)",qty:null,unit:"",price:-15566.63,sub:-778},
    ]},
  {id:4,number:4,title:"EIFS and Hardie",total:-19743,category:"Exterior/Facade",
    lines:[
      {desc:"Eliminate EIFS at Building Façade",qty:1,unit:"ls",price:-30000,sub:-30000},
      {desc:"Horizontal Hardie",qty:1,unit:"allow",price:12000,sub:12000},
      {desc:"Insurance (1.00%)",qty:null,unit:"",price:-30000,sub:-300},
      {desc:"Overhead and Fee (2.75%)",qty:null,unit:"",price:-18300,sub:-503},
      {desc:"Contingency (5.00%)",qty:null,unit:"",price:-18803.25,sub:-940},
    ]},
  {id:5,number:5,title:"Eliminate included scope for Fireplaces",total:-30043,category:"Interior/Mechanical",
    linkedItemId:13,
    veNote:"This removes only the fireplace infrastructure currently sitting in the budget (flues, tile, gas, electric). It does not include actual procurement of the fireplace units — that is priced separately in item 13. If fireplaces stay in scope, this item should be rejected and item 13's cost added instead.",
    lines:[
      {desc:"F&I fireplace flues",qty:1,unit:"ls",price:-4700,sub:-4700},
      {desc:"F&I fireplace tile",qty:1,unit:"allow",price:-8100,sub:-8100},
      {desc:"Fireplace Gas",qty:1,unit:"allow",price:-10000,sub:-10000},
      {desc:"Fireplace Electric",qty:1,unit:"allow",price:-5000,sub:-5000},
      {desc:"Insurance (1.00%)",qty:null,unit:"",price:-4700,sub:-47},
      {desc:"Overhead and Fee (2.75%)",qty:null,unit:"",price:-27847,sub:-766},
      {desc:"Contingency (5.00%)",qty:null,unit:"",price:-28612.79,sub:-1431},
    ]},
  {id:6,number:6,title:"Door 101B",total:-15859,category:"Doors/Hardware",
    lines:[
      {desc:"Eliminate 2hr Glass Door",qty:1,unit:"ls",price:-20000,sub:-20000},
      {desc:"F&I HM Door with sidelite",qty:1,unit:"allow",price:5500,sub:5500},
      {desc:"Insurance (1.00%)",qty:null,unit:"",price:-20000,sub:-200},
      {desc:"Overhead and Fee (2.75%)",qty:null,unit:"",price:-14700,sub:-404},
      {desc:"Contingency (5.00%)",qty:null,unit:"",price:-15104.25,sub:-755},
    ]},
  {id:7,number:7,title:"Breeze block",total:-22615,category:"Exterior/Facade",
    lines:[
      {desc:"F&I specified breeze block",qty:1,unit:"ls",price:-49120,sub:-49120},
      {desc:"Furnish screenwall allowance",qty:450,unit:"sf",price:25,sub:11250},
      {desc:"Install screenwall allowance",qty:120,unit:"hrs",price:145,sub:17400},
      {desc:"Insurance (1.00%)",qty:null,unit:"",price:-49120,sub:-491},
      {desc:"Overhead and Fee (2.75%)",qty:null,unit:"",price:-20961.20,sub:-576},
      {desc:"Contingency (5.00%)",qty:null,unit:"",price:-21537.63,sub:-1077},
    ]},
  {id:8,number:8,title:"Balconies",total:-49502,category:"Guest-facing/Exterior",
    lines:[
      {desc:"Furnish Aluminum balconies",qty:6,unit:"ea",price:-4664,sub:-27984},
      {desc:"Installation",qty:1,unit:"ls",price:-7500,sub:-7500},
      {desc:"Sliding Door",qty:6,unit:"ea",price:-3592.46,sub:-21555},
      {desc:"W3 Window",qty:6,unit:"ea",price:1905.99,sub:11436},
      {desc:"Insurance (1.00%)",qty:null,unit:"",price:-27984,sub:-280},
      {desc:"Overhead and Fee (2.75%)",qty:null,unit:"",price:-45882.66,sub:-1262},
      {desc:"Contingency (5.00%)",qty:null,unit:"",price:-47144.43,sub:-2357},
    ]},
  {id:9,number:9,title:"Sliding Doors & Juliets",total:-56071,category:"Guest-facing/Exterior",
    lines:[
      {desc:"Furnish Juliet Railings",qty:18,unit:"ea",price:-1054.70,sub:-18985},
      {desc:"Juliet Railing installation",qty:1,unit:"ls",price:-7500,sub:-7500},
      {desc:"Sliding Door",qty:15,unit:"ea",price:-3592.46,sub:-53887},
      {desc:"W3 Window",qty:15,unit:"ea",price:1905.99,sub:28590},
      {desc:"Insurance (1.00%)",qty:null,unit:"",price:-18984.60,sub:-190},
      {desc:"Overhead and Fee (2.75%)",qty:null,unit:"",price:-51971.50,sub:-1429},
      {desc:"Contingency (5.00%)",qty:null,unit:"",price:-53400.71,sub:-2670},
    ]},
  {id:10,number:10,title:"Landscaping",total:-52907,category:"Guest-facing/Site",
    lines:[
      {desc:"Landscape Plantings",qty:1,unit:"ls",price:-23900,sub:-23900},
      {desc:"Crushed granite",qty:1,unit:"ls",price:-24900,sub:-24900},
      {desc:"Insurance (1.00%)",qty:null,unit:"",price:-23900,sub:-239},
      {desc:"Overhead and Fee (2.75%)",qty:null,unit:"",price:-49039,sub:-1349},
      {desc:"Contingency (5.00%)",qty:null,unit:"",price:-50387.57,sub:-2519},
    ]},
  {id:11,number:11,title:"Under Paver Snow Melt",total:-32445,category:"Site/Operational",
    veNote:"Worth weighing against winter walkway safety and shoveling/salting labor at a Michigan property operating through winter, not a purely cosmetic cut.",
    lines:[
      {desc:"Furnish and Install snow melt under pavers",qty:1,unit:"ls",price:-29775,sub:-29775},
      {desc:"Insurance (1.00%)",qty:null,unit:"",price:-29775,sub:-298},
      {desc:"Overhead and Fee (2.75%)",qty:null,unit:"",price:-30072.75,sub:-827},
      {desc:"Contingency (5.00%)",qty:null,unit:"",price:-30899.75,sub:-1545},
    ]},
  {id:12,number:12,title:"Trash Enclosure",total:-17348,category:"Site/Back of house",
    lines:[
      {desc:"Foundation wall for Masonry",qty:1,unit:"ls",price:-8000,sub:-8000},
      {desc:"Masonry",qty:1,unit:"ls",price:-5000,sub:-5000},
      {desc:"Aluminum Gate",qty:1,unit:"ls",price:-8000,sub:-8000},
      {desc:"Fence",qty:1,unit:"ls",price:5000,sub:5000},
      {desc:"Insurance (1.00%)",qty:null,unit:"",price:-8000,sub:-80},
      {desc:"Overhead and Fee (2.75%)",qty:null,unit:"",price:-16080,sub:-442},
      {desc:"Contingency (5.00%)",qty:null,unit:"",price:-16522.20,sub:-826},
    ]},
  {id:13,number:13,title:"Furnish and install Fireplaces",total:155513,category:"Interior/Mechanical",isAdd:true,
    linkedItemId:5,
    veNote:"This is a cost add, not a savings item. It prices the actual fireplace units and installation, which are not currently in the budget at all — item 5 above only covers the infrastructure (flues, tile, gas, electric) already sitting in the budget. Keeping fireplaces means rejecting item 5 and adding this cost on top.",
    lines:[
      {desc:"Furnish and deliver (9) unit & (1) lobby fireplaces",qty:1,unit:"ls",price:132815.09,sub:132815},
      {desc:"Install fireplace logsets & connections",qty:1,unit:"allow",price:10000,sub:10000},
      {desc:"Insurance (1.00%)",qty:null,unit:"",price:132815.09,sub:1328},
      {desc:"Overhead and Fee (2.75%)",qty:null,unit:"",price:144143.24,sub:3964},
      {desc:"Contingency (5.00%)",qty:null,unit:"",price:148107.18,sub:7405},
    ]},
];

export const LESSONS_SEED=[
  {id:1,category:"Building Envelope",item:"Patio door threshold water intrusion",
    issue:"Water pitches in from the patio through the door threshold. Common, recurring issue across units.",
    owner:"SEEK / OSLO",severity:"High",status:"Flagged",photo_url:"",
    notes:"Highest priority item from the walkthrough list — building envelope/waterproofing detail, not a furniture fix. Needs a specific threshold/flashing detail reviewed for Barton before framing locks in."},
  {id:2,category:"Building Envelope",item:"Shower doors leak",
    issue:"Shower doors leak, generating a high volume of guest complaints.",
    owner:"SEEK / OSLO",severity:"High",status:"Flagged",photo_url:"",
    notes:"Recurring guest-facing complaint. Need to confirm Barton's shower door spec/detail addresses this rather than repeating it."},
  {id:3,category:"Building Envelope",item:"Sinks falling off the wall",
    issue:"Sinks are either too heavy for the mounting or were not installed correctly — falling off the wall in certain suites.",
    owner:"OSLO",severity:"High",status:"Flagged",photo_url:"",
    notes:"Safety issue, not cosmetic. Confirm Barton's sink mounting/blocking spec accounts for actual fixture weight before install."},
  {id:4,category:"Building Envelope",item:"Toilet paper holders fall out (no backing)",
    issue:"Toilet paper holders pull out of the wall from lack of anchor backing. Hooks, where installed, do have proper backing — a working model to copy. Drywall anchors are used in some other spots as a workaround.",
    owner:"OSLO",severity:"High",status:"Flagged",photo_url:"",
    notes:"Construction-phase blocking issue — needs to be in the framing spec for every wall-mounted bath accessory, not fixed after drywall is up. Use the hook detail as the standard."},
  {id:5,category:"Layout/Flow",item:"Closet doors removed in stacked W/D two-beds",
    issue:"Closet door quality overall is poor, and in the two-bedroom units with stacked washer/dryer, most closet doors had to be removed entirely — likely a clearance conflict.",
    owner:"Rebel House / SEEK",severity:"Medium",status:"Flagged",photo_url:"",
    notes:"Check Barton's two-bed unit plans for the same stacked W/D + closet door clearance conflict before it repeats."},
  {id:6,category:"Materials/Finishes",item:"Shelves peeling",
    issue:"Shelving surfaces are peeling.",
    owner:"Rebel House",severity:"Medium",status:"Flagged",photo_url:"",
    notes:""},
  {id:7,category:"Materials/Finishes",item:"Closet walls get black marks",
    issue:"Closet walls show black scuff marks over time (likely luggage/shoes).",
    owner:"Rebel House",severity:"Low",status:"Flagged",photo_url:"",
    notes:"Consider a more scuff-resistant finish or wainscoting in closets for Barton."},
  {id:8,category:"Furniture/FF&E",item:"Light fixture cover too fragile",
    issue:"Light fixture cover material is too fragile for regular guest/housekeeping use.",
    owner:"Rebel House",severity:"Medium",status:"Flagged",photo_url:"",
    notes:""},
  {id:9,category:"Furniture/FF&E",item:"Chair legs bent on arrival",
    issue:"Chair legs were thin and arrived bent from shipping. Appear fine now (after replacement/repair).",
    owner:"Rebel House",severity:"Low",status:"Resolved",photo_url:"",
    notes:"Worth a vendor packaging/QC note for future orders even though currently resolved."},
  {id:10,category:"MEP/Systems",item:"In-ground lights under the sign, buried in concrete",
    issue:"Two in-ground lights below the sign are embedded in concrete and now broken. Not repairable or replaceable without breaking out concrete.",
    owner:"SEEK / OSLO",severity:"High",status:"Flagged",photo_url:"",
    notes:"For Barton, avoid burying any serviceable fixture (lighting, electrical, low voltage) directly in concrete without an accessible sleeve, conduit, or removable cover. Anything that can fail needs a maintenance path."},
  {id:11,category:"Layout/Flow",item:"Salto keypad location far from front door",
    issue:"The Salto keypad at the front entrance is installed at an odd distance from the actual door — awkward for guests using it.",
    owner:"OSLO",severity:"Medium",status:"Flagged",photo_url:"",
    notes:"Confirm keypad placement is reviewed against actual door swing/approach for Barton, not just electrical rough-in convenience."},
];
